FROM nginx:1.20.0-alpine

RUN sed -i "s/v[0-9.]*\\/main/edge\\/main/" /etc/apk/repositories && \
    sed -i "s/v[0-9.]*\\/community/latest-stable\\/community/" /etc/apk/repositories && \
    apk update

#  CVE-2021-3518 : CRTICAL on libxml2 
RUN apk upgrade libjpeg-turbo freetype libxslt libgcrypt musl pcre